apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cadde-file-wrapper.fullname" . }}
  labels:
    {{- include "cadde-file-wrapper.labels" . | nindent 4 }}
data:
  CADDE_TOKEN_URL: {{ .Values.cadde.tokenUrl | quote }}
  CADDE_FILE_URL: {{ .Values.cadde.fileUrl | quote }}
  CADDE_RESOURCE_BASE_URL: {{ .Values.cadde.resourceBaseUrl | quote }}
  CADDE_RESOURCE_API_TYPE: {{ .Values.cadde.resourceApiType | quote }}
  CADDE_PROVIDER: {{ .Values.cadde.provider | quote }}
  CADDE_USER_ID: {{ .Values.cadde.userId | quote }}
