{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cadde-file-wrapper.fullname" . }}
  labels:
    {{- include "cadde-file-wrapper.labels" . | nindent 4 }}
  {{- if or .Values.certManager.enabled .Values.haproxy.enabled .Values.ingress.annotations }}
  annotations:
    {{- if .Values.certManager.enabled }}
    cert-manager.io/{{ .Values.certManager.issuerKind | lower }}: {{ .Values.certManager.issuerName | quote }}
    {{- end }}
    {{- if .Values.haproxy.enabled }}
    haproxy.org/timeout-connect: {{ .Values.haproxy.timeoutConnect | quote }}
    haproxy.org/timeout-client: {{ .Values.haproxy.timeoutClient | quote }}
    haproxy.org/timeout-server: {{ .Values.haproxy.timeoutServer | quote }}
    {{- if .Values.haproxy.rateLimitRequests }}
    haproxy.org/rate-limit-requests: {{ .Values.haproxy.rateLimitRequests | quote }}
    haproxy.org/rate-limit-period: {{ .Values.haproxy.rateLimitPeriod | quote }}
    {{- end }}
    {{- with .Values.haproxy.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cadde-file-wrapper.fullname" . }}
                port:
                  name: {{ .Values.service.port | quote }}
{{- end }}
