apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cadde-file-wrapper.fullname" . }}
  labels:
    {{- include "cadde-file-wrapper.labels" . | nindent 4 }}
type: Opaque
stringData:
  CADDE_AUTH_BASIC: {{ .Values.secret.authBasic | quote }}
  CADDE_PASSWORD: {{ .Values.secret.password | quote }}
