apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadde-file-wrapper.fullname" . }}
  labels:
    {{- include "cadde-file-wrapper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cadde-file-wrapper.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
